# Generated by Django 3.2.4 on 2021-06-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iskme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.TextField()),
                ('grade', models.CharField(max_length=50)),
                ('end_grade', models.CharField(blank=True, max_length=50)),
                ('learning_domain', models.CharField(max_length=100)),
                ('full_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
